2013-10-02 17:26:04,570 [Thread-10] ERROR StackTrace  - Full Stack Trace:
java.sql.SQLException: Already closed.
	at org.apache.commons.dbcp.PoolableConnection.close(PoolableConnection.java:114)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.close(PoolingDataSource.java:191)
	at org.springframework.jdbc.datasource.DataSourceUtils.doReleaseConnection(DataSourceUtils.java:333)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:211)
	at com.sun.proxy.$Proxy22.close(Unknown Source)
	at org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider.closeConnection(LocalDataSourceConnectionProvider.java:95)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.release(SuppliedConnectionProviderConnectionHelper.java:75)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:297)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:229)
	at org.hibernate.impl.SessionFactoryImpl.close(SessionFactoryImpl.java:961)
	at org.codehaus.groovy.grails.orm.hibernate.SessionFactoryProxy.close(SessionFactoryProxy.java:180)
	at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.destroy(AbstractSessionFactoryBean.java:228)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.destroy(LocalSessionFactoryBean.java:899)
	at org.codehaus.groovy.grails.orm.hibernate.ConfigurableLocalSessionFactoryBean.destroy(ConfigurableLocalSessionFactoryBean.java:245)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:211)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:500)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:476)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:445)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1078)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1052)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1000)
	at org.springframework.context.ConfigurableApplicationContext$close.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.codehaus.groovy.grails.support.DevelopmentShutdownHook$_setApplicationContext_closure1.doCall(DevelopmentShutdownHook.groovy:38)
	at org.codehaus.groovy.grails.support.DevelopmentShutdownHook$_setApplicationContext_closure1.doCall(DevelopmentShutdownHook.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:490)
	at java.lang.Thread.run(Thread.java:680)
2013-10-02 17:26:04,577 [Thread-10] ERROR StackTrace  - Full Stack Trace:
java.sql.SQLException: Already closed.
	at org.apache.commons.dbcp.PoolableConnection.close(PoolableConnection.java:114)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.close(PoolingDataSource.java:191)
	at java.lang.Thread.run(Thread.java:680)
2013-10-02 17:26:04,578 [Thread-10] ERROR StackTrace  - Full Stack Trace:
java.sql.SQLException: Already closed.
	at org.apache.commons.dbcp.PoolableConnection.close(PoolableConnection.java:114)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.close(PoolingDataSource.java:191)
	at java.lang.Thread.run(Thread.java:680)
2013-10-02 17:26:04,578 [Thread-10] ERROR StackTrace  - Full Stack Trace:
java.sql.SQLException: Already closed.
	at org.apache.commons.dbcp.PoolableConnection.close(PoolableConnection.java:114)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.close(PoolingDataSource.java:191)
	at java.lang.Thread.run(Thread.java:680)
